"""
export_locations.py
TransitAI Location Export Utility

Reads all locations from database/transit.db, deduplicates, sorts, and generates:
  - database/master_locations.csv
  - database/master_locations.json
  - database/location_report.md

Usage:
    python export_locations.py
"""

import sqlite3
import csv
import json
import os
from collections import defaultdict
from typing import List, Dict, Any

# ─── Paths ────────────────────────────────────────────────────────────────────
BASE_DIR      = os.path.dirname(os.path.abspath(__file__))
DB_PATH       = os.path.join(BASE_DIR, "database", "transit.db")
DB_DIR        = os.path.join(BASE_DIR, "database")
CSV_PATH      = os.path.join(DB_DIR, "master_locations.csv")
JSON_PATH     = os.path.join(DB_DIR, "master_locations.json")
REPORT_PATH   = os.path.join(DB_DIR, "location_report.md")

# ─── Database Query ───────────────────────────────────────────────────────────

def fetch_locations(db_path: str) -> List[Dict[str, Any]]:
    """Fetches all location rows from the SQLite database."""
    conn = sqlite3.connect(db_path)
    conn.row_factory = sqlite3.Row
    cursor = conn.cursor()
    cursor.execute("""
        SELECT id, name, city, state, latitude, longitude, type
        FROM locations
        ORDER BY state, city, name
    """)
    rows = [dict(r) for r in cursor.fetchall()]
    conn.close()
    return rows

# ─── Deduplication ────────────────────────────────────────────────────────────

def deduplicate(locations: List[Dict[str, Any]]):
    """
    Removes exact duplicates (same name + city + state).
    Returns (unique_rows, duplicate_rows).
    """
    seen = {}
    duplicates = []
    unique = []

    for loc in locations:
        key = (loc["name"].strip().lower(), loc["city"].strip().lower(), loc["state"].strip().lower())
        if key in seen:
            duplicates.append(loc)
        else:
            seen[key] = True
            unique.append(loc)

    return unique, duplicates

# ─── Sorting ──────────────────────────────────────────────────────────────────

def sort_locations(locations: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
    """Sorts locations by State → City → Name."""
    return sorted(
        locations,
        key=lambda r: (r["state"].lower(), r["city"].lower(), r["name"].lower())
    )

# ─── CSV Export ───────────────────────────────────────────────────────────────

def export_csv(locations: List[Dict[str, Any]], path: str):
    """Writes the location list to a CSV file."""
    fieldnames = ["id", "name", "city", "state", "latitude", "longitude", "type"]
    with open(path, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        for loc in locations:
            writer.writerow({k: loc.get(k, "") for k in fieldnames})

# ─── JSON Export ──────────────────────────────────────────────────────────────

def export_json(locations: List[Dict[str, Any]], path: str):
    """Writes the location list to a pretty-printed JSON file."""
    payload = {
        "total": len(locations),
        "locations": locations
    }
    with open(path, "w", encoding="utf-8") as f:
        json.dump(payload, f, indent=2, ensure_ascii=False)

# ─── Statistics Helpers ───────────────────────────────────────────────────────

def stats_by(locations: List[Dict[str, Any]], key: str) -> Dict[str, int]:
    counts: Dict[str, int] = defaultdict(int)
    for loc in locations:
        counts[loc[key]] += 1
    return dict(sorted(counts.items()))

def missing_coords(locations: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
    return [
        loc for loc in locations
        if loc.get("latitude") is None or loc.get("longitude") is None
    ]

# ─── Markdown Report ──────────────────────────────────────────────────────────

def export_report(
    locations: List[Dict[str, Any]],
    duplicates: List[Dict[str, Any]],
    path: str
):
    """Writes the location_report.md file."""
    by_state = stats_by(locations, "state")
    by_city  = stats_by(locations, "city")
    no_coords = missing_coords(locations)

    lines = [
        "# TransitAI — Location Master Report\n",
        f"**Generated by:** `export_locations.py`\n",
        "---\n",
        "## Overview\n",
        f"| Metric | Count |",
        f"|--------|-------|",
        f"| Total Locations | {len(locations)} |",
        f"| States Covered  | {len(by_state)} |",
        f"| Cities Covered  | {len(by_city)} |",
        f"| Duplicate Records Found | {len(duplicates)} |",
        f"| Records with Missing Coordinates | {len(no_coords)} |",
        "",
        "---\n",
        "## Locations per State\n",
        "| State | Count |",
        "|-------|-------|",
    ]
    for state, count in by_state.items():
        lines.append(f"| {state} | {count} |")

    lines += [
        "",
        "---\n",
        "## Locations per City\n",
        "| City | State | Count |",
        "|------|-------|-------|",
    ]
    for loc in sorted(locations, key=lambda x: (x["state"], x["city"])):
        pass  # just to keep a consistent sort

    # Build unique city→state→count table
    city_state: Dict[str, str] = {}
    for loc in locations:
        city_state[loc["city"]] = loc["state"]
    city_count = stats_by(locations, "city")
    for city in sorted(city_count.keys(), key=lambda c: (city_state.get(c, ""), c)):
        lines.append(f"| {city} | {city_state.get(city, '')} | {city_count[city]} |")

    lines += [
        "",
        "---\n",
        "## Duplicate Records\n",
    ]
    if duplicates:
        lines += [
            "| ID | Name | City | State |",
            "|----|------|------|-------|",
        ]
        for d in duplicates:
            lines.append(f"| {d['id']} | {d['name']} | {d['city']} | {d['state']} |")
    else:
        lines.append("✅ No duplicate records found.\n")

    lines += [
        "",
        "---\n",
        "## Records with Missing Coordinates\n",
    ]
    if no_coords:
        lines += [
            "| ID | Name | City | State |",
            "|----|------|------|-------|",
        ]
        for loc in no_coords:
            lines.append(f"| {loc['id']} | {loc['name']} | {loc['city']} | {loc['state']} |")
    else:
        lines.append("✅ All records have valid coordinates.\n")

    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

# ─── Console Summary ──────────────────────────────────────────────────────────

def print_summary(locations: List[Dict[str, Any]]):
    by_state = stats_by(locations, "state")
    border = "=" * 49

    print(f"\n{border}")
    print("  TransitAI Location Export")
    print(f"{border}")
    print(f"  Total Locations: {len(locations)}")
    print()

    for state, count in by_state.items():
        print(f"  {state}: {count}")

    print()
    print("  Files Generated:")
    print(f"  database/master_locations.csv")
    print(f"  database/master_locations.json")
    print(f"  database/location_report.md")
    print(f"{border}\n")

# ─── Entry Point ──────────────────────────────────────────────────────────────

def main():
    if not os.path.exists(DB_PATH):
        print(f"[ERROR] Database not found at: {DB_PATH}")
        print("  Run rebuild_database.py first to initialise the database.")
        return

    os.makedirs(DB_DIR, exist_ok=True)

    # 1. Fetch
    raw_locations = fetch_locations(DB_PATH)

    # 2. Deduplicate
    unique_locations, duplicates = deduplicate(raw_locations)

    if duplicates:
        print(f"[WARN] {len(duplicates)} duplicate record(s) removed.")

    # 3. Sort
    sorted_locations = sort_locations(unique_locations)

    # 4. Export CSV
    export_csv(sorted_locations, CSV_PATH)

    # 5. Export JSON
    export_json(sorted_locations, JSON_PATH)

    # 6. Export Markdown report
    export_report(sorted_locations, duplicates, REPORT_PATH)

    # 7. Print summary
    print_summary(sorted_locations)


if __name__ == "__main__":
    main()
